blank_issues_enabled: false
contact_links:
  - name: ğŸ’¼ Suporte Administrativo
    url: https://wa.me/5544998784304
    about: Fale diretamente com o financeiro ou gestÃ£o de contratos.

  - name: ğŸ†˜ Suporte TÃ©cnico
    url: https://wa.me/5545988383189
    about: Canal para dÃºvidas rÃ¡pidas ou situaÃ§Ãµes crÃ­ticas de paralisia.
